import type { Activity, Incident, Service, Ticket, User } from "@/types";

// A single org's worth of data — Relay is org-scoped throughout (README §5).
const ORG_ID = "org_1";
const now = Date.now();
const minutesAgo = (m: number) => new Date(now - m * 60_000).toISOString();
const hoursAgo = (h: number) => minutesAgo(h * 60);
const daysAgo = (d: number) => hoursAgo(d * 24);

export const users: User[] = [
  {
    id: "u_maya",
    orgId: ORG_ID,
    email: "maya@kestrel.dev",
    name: "Maya Reyes",
    role: "MANAGER",
    initials: "MR",
    active: true,
  },
  {
    id: "u_josh",
    orgId: ORG_ID,
    email: "josh@kestrel.dev",
    name: "Josh Dietrich",
    role: "MEMBER",
    initials: "JD",
    active: true,
  },
  {
    id: "u_sana",
    orgId: ORG_ID,
    email: "sana@kestrel.dev",
    name: "Sana Kapoor",
    role: "MEMBER",
    initials: "SK",
    active: true,
  },
  {
    id: "u_leo",
    orgId: ORG_ID,
    email: "leo@kestrel.dev",
    name: "Leo Fontaine",
    role: "MEMBER",
    initials: "LF",
    active: true,
  },
  {
    id: "u_priya",
    orgId: ORG_ID,
    email: "priya@kestrel.dev",
    name: "Priya Nair",
    role: "MEMBER",
    initials: "PN",
    active: true,
  },
];

const userById = Object.fromEntries(users.map((u) => [u.id, u]));

export const services: Service[] = [
  {
    id: "svc_payments",
    orgId: ORG_ID,
    name: "Payments API",
    description: "Card authorization and capture",
    status: "OPERATIONAL",
    latencyMs: 118,
    errorRate: 0.12,
    version: 14,
    updatedAt: minutesAgo(2),
    archived: false,
    sessionLatencyTrend: [112, 115, 109, 121, 118],
  },
  {
    id: "svc_checkout",
    orgId: ORG_ID,
    name: "Checkout",
    description: "Cart, pricing, and order creation",
    status: "DEGRADED",
    latencyMs: 342,
    errorRate: 4.86,
    version: 27,
    updatedAt: minutesAgo(1),
    archived: false,
    sessionLatencyTrend: [190, 205, 260, 310, 342],
  },
  {
    id: "svc_auth",
    orgId: ORG_ID,
    name: "Auth",
    description: "Session issuance and token refresh",
    status: "OPERATIONAL",
    latencyMs: 76,
    errorRate: 0.04,
    version: 9,
    updatedAt: minutesAgo(4),
    archived: false,
    sessionLatencyTrend: [80, 78, 74, 77, 76],
  },
  {
    id: "svc_search",
    orgId: ORG_ID,
    name: "Search",
    description: "Catalog indexing and query",
    status: "OPERATIONAL",
    latencyMs: 203,
    errorRate: 0.31,
    version: 22,
    updatedAt: minutesAgo(6),
    archived: false,
    sessionLatencyTrend: [198, 210, 205, 200, 203],
  },
  {
    id: "svc_notify",
    orgId: ORG_ID,
    name: "Notifications",
    description: "Email, SMS, and push dispatch",
    status: "OUTAGE",
    latencyMs: 0,
    errorRate: 100,
    version: 31,
    updatedAt: minutesAgo(3),
    archived: false,
    sessionLatencyTrend: [220, 890, 0, 0, 0],
  },
  {
    id: "svc_billing",
    orgId: ORG_ID,
    name: "Billing",
    description: "Invoicing and subscription state",
    status: "OPERATIONAL",
    latencyMs: 145,
    errorRate: 0.08,
    version: 11,
    updatedAt: minutesAgo(9),
    archived: false,
    sessionLatencyTrend: [150, 148, 144, 146, 145],
  },
];

export const tickets: Ticket[] = [
  {
    id: "t_1",
    orgId: ORG_ID,
    title: "Checkout 500s on discount codes >10% off",
    description: "",
    status: "IN_PROGRESS",
    priority: "URGENT",
    assigneeId: "u_josh",
    creatorId: "u_maya",
    version: 4,
    createdAt: hoursAgo(2),
    updatedAt: minutesAgo(5),
  },
  {
    id: "t_2",
    orgId: ORG_ID,
    title: "Notification worker stuck retrying dead queue",
    description: "",
    status: "IN_PROGRESS",
    priority: "URGENT",
    assigneeId: "u_sana",
    creatorId: "u_sana",
    version: 3,
    createdAt: hoursAgo(1),
    updatedAt: minutesAgo(2),
  },
  {
    id: "t_3",
    orgId: ORG_ID,
    title: "Search returns stale prices for ~30s after update",
    description: "",
    status: "OPEN",
    priority: "HIGH",
    assigneeId: "u_leo",
    creatorId: "u_priya",
    version: 1,
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(5),
  },
  {
    id: "t_4",
    orgId: ORG_ID,
    title: "Add pagination to billing invoice export",
    description: "",
    status: "OPEN",
    priority: "LOW",
    assigneeId: null,
    creatorId: "u_maya",
    version: 1,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "t_5",
    orgId: ORG_ID,
    title: "Auth refresh token rotation off by one",
    description: "",
    status: "OPEN",
    priority: "MEDIUM",
    assigneeId: "u_priya",
    creatorId: "u_leo",
    version: 2,
    createdAt: hoursAgo(8),
    updatedAt: hoursAgo(3),
  },
  {
    id: "t_6",
    orgId: ORG_ID,
    title: "Payments webhook signature check flaky in staging",
    description: "",
    status: "BLOCKED",
    priority: "HIGH",
    assigneeId: "u_josh",
    creatorId: "u_josh",
    version: 3,
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(6),
  },
  {
    id: "t_7",
    orgId: ORG_ID,
    title: "Checkout cart total rounding mismatch (JPY)",
    description: "",
    status: "BLOCKED",
    priority: "MEDIUM",
    assigneeId: "u_sana",
    creatorId: "u_maya",
    version: 2,
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(10),
  },
  {
    id: "t_8",
    orgId: ORG_ID,
    title: "Add dark-mode icon set to notification emails",
    description: "",
    status: "RESOLVED",
    priority: "LOW",
    assigneeId: "u_leo",
    creatorId: "u_priya",
    version: 5,
    createdAt: daysAgo(3),
    updatedAt: hoursAgo(12),
  },
  {
    id: "t_9",
    orgId: ORG_ID,
    title: "Billing double-charged trial-to-paid conversions",
    description: "",
    status: "RESOLVED",
    priority: "URGENT",
    assigneeId: "u_maya",
    creatorId: "u_sana",
    version: 6,
    createdAt: daysAgo(4),
    updatedAt: daysAgo(1),
  },
  {
    id: "t_10",
    orgId: ORG_ID,
    title: "Search facet counts ignore region filter",
    description: "",
    status: "OPEN",
    priority: "MEDIUM",
    assigneeId: "u_priya",
    creatorId: "u_leo",
    version: 1,
    createdAt: hoursAgo(4),
    updatedAt: hoursAgo(4),
  },
];

export const incidents: Incident[] = [
  {
    id: "i_1",
    orgId: ORG_ID,
    title: "Notification delivery completely down",
    description:
      "All channels failing after queue backlog exceeded retry budget.",
    status: "INVESTIGATING",
    severity: "CRITICAL",
    responderId: "u_sana",
    createdAt: minutesAgo(38),
    resolvedAt: null,
    version: 5,
    serviceIds: ["svc_notify"],
    ticketIds: ["t_2"],
  },
  {
    id: "i_2",
    orgId: ORG_ID,
    title: "Elevated errors on checkout with discount codes",
    description: "Discount codes over 10% trigger a pricing-service 500.",
    status: "IDENTIFIED",
    severity: "HIGH",
    responderId: "u_josh",
    createdAt: hoursAgo(2),
    resolvedAt: null,
    version: 3,
    serviceIds: ["svc_checkout"],
    ticketIds: ["t_1"],
  },
  {
    id: "i_3",
    orgId: ORG_ID,
    title: "Search latency creeping up since deploy",
    description: "p95 latency up ~15% since the 14:20 index rebuild.",
    status: "MONITORING",
    severity: "LOW",
    responderId: "u_leo",
    createdAt: hoursAgo(5),
    resolvedAt: null,
    version: 2,
    serviceIds: ["svc_search"],
    ticketIds: [],
  },
  // Resolved incidents give the incidents list something to show once the
  // status filter moves off the active ones the dashboard panel surfaces
  // (README §15 only shows *active* incidents there; the full list also
  // needs to answer "is it getting better" for things already closed out).
  {
    id: "i_4",
    orgId: ORG_ID,
    title: "Billing double-charge on trial conversion",
    description:
      "A race between the trial-expiry job and the upgrade webhook double-captured card payments for same-day conversions.",
    status: "RESOLVED",
    severity: "HIGH",
    responderId: "u_maya",
    createdAt: daysAgo(2),
    resolvedAt: daysAgo(1),
    version: 6,
    serviceIds: ["svc_billing"],
    ticketIds: ["t_9"],
  },
  {
    id: "i_5",
    orgId: ORG_ID,
    title: "Auth sessions intermittently rejected after deploy",
    description:
      "A clock-skew edge case in refresh-token validation rejected ~2% of otherwise-valid sessions for about 40 minutes.",
    status: "RESOLVED",
    severity: "MEDIUM",
    responderId: "u_priya",
    createdAt: daysAgo(3),
    resolvedAt: daysAgo(3),
    version: 4,
    serviceIds: ["svc_auth"],
    ticketIds: [],
  },
];

export const activities: Activity[] = [
  {
    id: "a_1",
    orgId: ORG_ID,
    actorId: null,
    action: "SERVICE_STATUS_CHANGED",
    targetType: "service",
    targetId: "svc_notify",
    metadata: { from: "DEGRADED", to: "OUTAGE" },
    createdAt: minutesAgo(3),
  },
  {
    id: "a_2",
    orgId: ORG_ID,
    actorId: "u_sana",
    action: "INCIDENT_STATUS_CHANGED",
    targetType: "incident",
    targetId: "i_1",
    metadata: { from: "IDENTIFIED", to: "INVESTIGATING" },
    createdAt: minutesAgo(6),
  },
  {
    id: "a_3",
    orgId: ORG_ID,
    actorId: "u_sana",
    action: "TICKET_STATUS_CHANGED",
    targetType: "ticket",
    targetId: "t_2",
    metadata: { from: "OPEN", to: "IN_PROGRESS" },
    createdAt: minutesAgo(9),
  },
  {
    id: "a_4",
    orgId: ORG_ID,
    actorId: null,
    action: "SERVICE_STATUS_CHANGED",
    targetType: "service",
    targetId: "svc_checkout",
    metadata: { from: "OPERATIONAL", to: "DEGRADED" },
    createdAt: minutesAgo(14),
  },
  {
    id: "a_5",
    orgId: ORG_ID,
    actorId: "u_josh",
    action: "INCIDENT_TICKET_LINKED",
    targetType: "incident",
    targetId: "i_2",
    metadata: { ticketTitle: "Checkout 500s on discount codes >10% off" },
    createdAt: minutesAgo(17),
  },
  {
    id: "a_6",
    orgId: ORG_ID,
    actorId: "u_josh",
    action: "TICKET_ASSIGNED",
    targetType: "ticket",
    targetId: "t_1",
    metadata: { assignee: "Josh Dietrich" },
    createdAt: minutesAgo(18),
  },
  {
    id: "a_7",
    orgId: ORG_ID,
    actorId: "u_maya",
    action: "INCIDENT_CREATED",
    targetType: "incident",
    targetId: "i_2",
    metadata: { title: "Elevated errors on checkout with discount codes" },
    createdAt: hoursAgo(2),
  },
  {
    id: "a_8",
    orgId: ORG_ID,
    actorId: "u_leo",
    action: "INCIDENT_SEVERITY_CHANGED",
    targetType: "incident",
    targetId: "i_3",
    metadata: { from: "MEDIUM", to: "LOW" },
    createdAt: hoursAgo(3),
  },
  {
    id: "a_9",
    orgId: ORG_ID,
    actorId: "u_priya",
    action: "TICKET_CREATED",
    targetType: "ticket",
    targetId: "t_10",
    metadata: { title: "Search facet counts ignore region filter" },
    createdAt: hoursAgo(4),
  },
  {
    id: "a_10",
    orgId: ORG_ID,
    actorId: "u_maya",
    action: "INCIDENT_RESOLVED",
    targetType: "incident",
    targetId: "i_4",
    metadata: { title: "Billing double-charge on trial conversion" },
    createdAt: daysAgo(1),
  },
];

// Presence is never persisted (README §14) — this stands in for what the
// Realtime Presence channel would report at request time.
export const onlineUserIds = new Set(["u_maya", "u_josh", "u_sana"]);

export function resolveUser(id: string | null): User | null {
  if (!id) return null;
  return userById[id] ?? null;
}

export const currentOrgName = "Kestrel Commerce";
